### ISSUE TITLE
Trigger Fixer 0.1.0.0 does not replace triggers that contain symbols (with or without letters and numbers)

### ISSUE THREAD

**Issue by MrFox14** [EchoDevG/trigger-fixer#4]
Trigger Fixer 0.1.0.0 does not replace triggers that contain symbols (with or without letters and numbers), such as: !, ), #, $, %, ^, @human, happy!
STEPS TO REPRODUCE:
1. Open Chrome;
2. Click the Extensions Icon;
2. Click the Trigger Fixer 0.1.0.0 Extension;
3. Make a new trigger that contains a symbol and replace it with anything as you'll like (but in this, we will use "@" as the trigger and "person" as the replacing word);
4. Submit it;
5. Open a new tab and search "@" in Google and/or any other search engine.

EXPECTED RESULTS: Trigger Fixer will automatically replace all search results that has the trigger "@" with the word "human".

ACTUAL RESULTS: Trigger Fixer does not replace the trigger "@" with "human".

**Comment by Mistyttm** [comment]
Then intention of this extension is to allow users to censor triggering word and phrases on their own. Allowing users to block symbols create an unusable experience. On top of this is the fact that at this point in time, for myself and Echo, it is technically impossible for us to do.

Allowing users to block symbols causes more problems than it fixes.

This will not be implemented.
