### ISSUE TITLE
Trigger Fixer does not work in Chrome Web Store

### ISSUE THREAD

**Issue by MrFox14** [EchoDevG/trigger-fixer#5]
Description: Trigger Fixer does not work ANYWHERE (including the reviews) in Chrome Web Store, EXCEPT for the title of an attached video(sourced from another website) in the Overview of an extension/theme.

STEPS TO REPRODUCE:
1. Go to Chrome;
2. Click the extensions icon;
3. Click Trigger Fixer 0.1.0.0;
4. Click Edit Trigger List;
5. Make a word censored/replaced by filling the first box with your trigger and the second box to what you want your trigger to be replaced with(but as an example, we will use the word "mode" for the trigger and use "choice" for the replacing word);
6. Navigate to chrome.google.com/webstore/ ;
7. In the search box, type the word "mode"(trigger word) ;
8. Press Enter

EXPECTED RESULTS: Trigger Fixer will replace the word "mode"(trigger word) contained in the search results with the word "choice"(replacing word).
ACTUAL RESULTS: Trigger Fixer did not change anything in the page except the title of an attached video(sourced from another website) in the Overview of an extension/theme.
 
(Please check if it works for you, and if it does, then you can ignore this issue.)

**Comment by Mistyttm** [comment]
Okay, I finally understand this issue. This isn't a bug. This is the way that Chrome is set up. The chrome webstore is a protected page inside chrome. testing using the firefox version, the chrome webstore is affected. But firefox pages are protected. If the firefox pages were tested on chrome, they would then be affected.

So this isn't a bug, just a protected page :)
